runtime: nodejs18

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  # Serve static files from the React app's build folder
  - url: /
    static_files: client/build/index.html
    upload: client/build/index.html

  - url: /
    static_dir: client/build
